### ISSUE TITLE
How does the user describe the desired trajectory from the GUI?

### ISSUE THREAD

**Issue by adaldo** [KTH-AEROWORKS/sml_clean#3]
So far the `Trajectory` objects can be built only by calling the constructor explicitly (`my_circle = CircleTrajectory(radius, speed, offset, rotation)`). But the constructor takes complex array parameters (such as offset and rotation) which the user cannot just "type" in the GUI.

How did we get the trajectories to be defined by the user in the GUI? I guess that we let the user specify a smaller number of parameters (for example, height, radius and speed for a circle trajectory), and use defaults for all the rest, then call a constructor from **outside** the class. This works fine, but then, whenever we add a different type of trajectory to the project (for example, `EightTrajectory`), we need to modify the GUI to account for a new interface for constructing that type of object.

Is this more or less the current picture, or am I missing something?

**Comment by ppereiraKTH** [comment]
For example, in the gui and for the circle, you must specify the radius and the speed. And those are sent to the construct the circle object.

Now, for the offset and the rotation, the user can also specify those on the gui, but to be more correct, this parameters should be specified in a "tab" that is not specific to circle; rather a tab that works for all trajectories.

Also, quick note: Manuel did something that I will try to reuse, where it is easy for the user to define a sequence of trajectories: something like: first 10 seconds, stay in point A, next 15 seconds, describe circle with radius ..., next 10 seconds describe ... and so on

**Comment by adaldo** [comment]
Ok, I get it, so the GUI has a different tab for each kind of trajectory, and on each tab the user can specify the parameters that are specific to that trajectory. Plus there is a special tab for specifying offset and rotation that applies to all trajectories.

But how does the GUI know what parameters should be given for each trajectory? For example, how does it know that, if I pick "circle", it should ask me for a radius and a speed? If I make a new trajectory, say `LineTrajectory`, how does the GUI know that it should ask me for a displacement and a speed? (the initial point would be the offset). Do we need to hard-code a set of buttons for each new type of trajectory?

**Edit** : Anyways, no need to go in-depth now. We can discuss on Tuesday and decide on what is the "best" way to let the GUI know the parameters that each trajectory needs to be instantiated. I think that this will have some impact, because, whatever mechanism we go for, we will probably apply it to the simulators and controllers as well. (They have the same issue where different controllers/simulators require a different list of parameters to be instantiated.)

For now, I just put an example that shows how to access the parameter list of a constructor.
In this way, the user can be prompted for a different set of parameters according to what kind of trajectory she wants to make. I let the parameters be put by command line, but I guess the GUI can do the same.

And sorry for all the gibberish, but I am having too much fun right now u.u

**Comment by ppereiraKTH** [comment]
So, as it is, each tab on the GUI needs to be made individually for each trajectory.

We can discuss how to do this better.
